### ISSUE TITLE
Why the angles are all nearly the same?

### ISSUE THREAD

**Issue by 13331151** [cvlab-epfl/LIFT#11]
Hi,
  Jack again,
  I recently trained several descriptor models, but they all failed to meet the performance as yours. And the possible difference between yours and mine is the dataset (and maybe the training strategy, but I thought it didn't matter that much). Then I found that the angles generated by your model are all nearly the same(about 135)...Could you give me any explanation, please?  Thanks in advance. @kmyid

**Comment by kmyi** [comment]
Hi Jack,

 >  the dataset (and maybe the training strategy, but I thought it didn't matter that much). 

This is quite *critical* in the final performance. We tried training on various datasets, and the best performance was achieved when photo tourism datasets were used. Also, the training strategy, i.e. mining and pair settings are also an important factor. As the network is complex, it's not really trivial to train.

> Then I found that the angles generated by your model are all nearly the same(about 135)...Could you give me any explanation, please? 

Due to the dataset having a bias of pictures being mostly upright, the current trained model is trained is *not* fully rotation invariant. It has a relatively small operating angle of -30~30 degrees. We are training a model that does not suffer from this as a side project, and are planning to release it soon. The orientation-benchmark repo already has the fully rotation invariant model for the CVPR2016 paper.

Cheers,
Kwang

**Comment by 13331151** [comment]
Hi Kwang,
  So do you use SIFT's orientation to generate the dataset training the descriptors network or just make a pair of patch have a same orientation? Thanks.

**Comment by kmyi** [comment]
Hi Jack,

> So do you use SIFT's orientation to generate the dataset training the descriptors network or just make a pair of patch have a same orientation? Thanks.

IIRC, we indeed use the SIFT orientations. :-)

Regards,
Kwang

**Comment by 13331151** [comment]
Thanks, Kwang! I will retry the training and add the hard sample mining. Best wishes! :)

**Comment by 13331151** [comment]
A little more question, are you using photo tourism datasets from http://phototour.cs.washington.edu/patches/default.htm , and do you do any modification? Thank you very much @kmyid

**Comment by kmyi** [comment]
> A little more question, are you using photo tourism datasets from http://phototour.cs.washington.edu/patches/default.htm , and do you do any modification? 

No. We use the piccadilly circus and roman forum phototourism dataset and extract patches ourselves :-)
