### ISSUE TITLE
Speed of code

### ISSUE THREAD

**Issue by andrefaraujo** [cvlab-epfl/LIFT#2]
Hello,
Thanks for releasing the code!

I've been playing with it and I noticed that it is a little slow. My measurements for the test image provided in the repo are (using a very recent TitanX):
- 1m33s for keypoint detection
- 13.9s for orientation estimation
- 13.s for descriptor computation
TOTAL: 2min/image

Questions:
- Does this timing agree with what you experience when using the code? [hopefully I am not doing something wrong! :)]
- Are you planning to release a faster version of the code? I am trying to use LIFT for large-scale image retrieval (eg, think of replacing SIFT in this context). Do you think this is currently possible?

Thank you again!

**Comment by kmyi** [comment]
Hello,

Thanks for using the code!. Currently, we just wanted to release something fast, and the released version may suffer some issues due to theano compilation time. We are working on a C++ implementation as well as making a release version that does not have this issue!

Given that, it still seems quite slower than what we've observed in our tests. Let me get back to you after looking into what's going on.

Cheers,
Kwang

**Comment by andrefaraujo** [comment]
Thanks for the quick reply, Kwang.
Looking forward to hear back from you soon
