### ISSUE TITLE
is the descriptors matched by the standard vl_ubcmatch?

### ISSUE THREAD

**Issue by RuibinMa** [cvlab-epfl/LIFT#31]
(Also asked in the tf-lift repo.) I'm wondering what method you used to match the descriptors? Is it the standard vl_ubcmatch()? I want to ask this because the output descriptors are not [0-255] integers, which a lot of software takes. I don't know whether it affects anything. Thank you so much!

**Comment by kmyi** [comment]
Please don't duplicate issues or necro closed threads. It's only going to cause spam for everybody that have notifications on. I'm going to simply close the other issue tracker.

We use simple nearest neighbor matching as written in the paper. ubcmatch is not good, since I believe it does a ratio test, which actually is geared towards SIFT. It rather harms our descriptor performance severely if you do that.
